### PR TITLE
Release 3.30.0

### PR DESCRIPTION
**Pull request by cklewin**

### CODE REVIEW

**Comment by cklewin** [comment]
### Ready to release v3.30.0
---
**Approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/395/files) to proceed.
**Delete** the [release/3.30.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Review by testuser9891 — APPROVED** [review]

**Comment by cklewin** [comment]
:green_circle: Release v3.30.0 created.

**Comment by cklewin** [comment]
:green_circle: The code freeze has been lifted, and the `develop` branch has been unlocked.

**Comment by cklewin** [comment]
### Not ready to release
---
:red_circle: Release tag v3.30.0 already exists
:red_circle: Not Found

---
**Resolve these errors and approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/395/files) to proceed.
**Delete** the [release/3.30.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Comment by cklewin** [comment]
:red_circle: **An error occurred:** Release validation failed

**Comment by cklewin** [comment]
### Not ready to release
---
:red_circle: Not Found

---
**Resolve these errors and approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/395/files) to proceed.
**Delete** the [release/3.30.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Comment by cklewin** [comment]
:red_circle: **An error occurred:** Release validation failed

**Pull request merged**
