### PR TITLE
Release 3.26.0

### PR DESCRIPTION
**Pull request by cklewin**

### CODE REVIEW

**Comment by cklewin** [comment]
:warning: A code freeze was requested, but an error occurred: The develop branch is locked, but not by this pull request (371) - check the repository variable: `RELEASE_MANAGER_LOCK_PR` and the branch protection rules for the `develop` branch

:fire: You may still proceed with the release, but there will be **no** code freeze in effect.

**Comment by cklewin** [comment]
### Not ready to release
---
:red_circle: The develop branch is locked, but not by this pull request (371) - check the repository variable: `RELEASE_MANAGER_LOCK_PR` and the branch protection rules for the `develop` branch

---
**Resolve these errors and approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/371/files) to proceed.
**Delete** the [release/3.26.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Review by testuser9891 — APPROVED** [review]

**Comment by cklewin** [comment]
### Not ready to release
---
:red_circle: The develop branch is locked, but not by this pull request (371) - check the repository variable: `RELEASE_MANAGER_LOCK_PR` and the branch protection rules for the `develop` branch

---
**Resolve these errors and approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/371/files) to proceed.
**Delete** the [release/3.26.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Comment by cklewin** [comment]
:red_circle: **An error occurred:** Release validation failed

**Pull request closed without merging**
