### PR TITLE
Release 3.24.0

### PR DESCRIPTION
**Pull request by cklewin**

### CODE REVIEW

**Comment by cklewin** [comment]
:interrobang: A code freeze was requested, but the repository variable: `RELEASE_MANAGER_LOCK_PR` is already set - check the repository variable: `RELEASE_MANAGER_LOCK_PR`, this is most likely left over from a previous release that failed to clean up.

You may proceed with the release, but there is no code freeze in affect.

**Review by testuser9891 — APPROVED** [review]

**Comment by cklewin** [comment]
### Not ready to release
---
:red_circle: The develop branch is locked, but not by this pull request (360) - check the repository variable: `RELEASE_MANAGER_LOCK_PR` and the branch protection rules for the `develop` branch

---
**Resolve these errors and approve** this [pull request](https://github.com/jevaka-test-organization/test/pull/360/files) to proceed.
**Delete** the [release/3.24.0 branch](https://github.com/jevaka-test-organization/test/branches) to abort.

**Review by testuser9891 — APPROVED** [review]

**Comment by cklewin** [comment]
:green_circle: Release v3.24.0 created.

**Comment by cklewin** [comment]
:green_circle: The develop branch is now 3.25.0-alpha.

**Pull request merged**
