### PR TITLE
Release 3.11.0

### PR DESCRIPTION
**Pull request by cklewin**

### CODE REVIEW

**Comment by cklewin** [comment]
The develop branch is now locked.

**Comment by cklewin** [comment]
Ready to release v3.11.0.

Approve this pull request to proceed.

Delete the release branch to abort.

**Review by testuser9891 — APPROVED** [review]

**Comment by cklewin** [comment]
Release v3.11.0 created.

**Comment by cklewin** [comment]
The develop branch is now 3.12.0-alpha.

**Pull request merged**
